@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60


skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam SequenceBoxBackgroundColor AliceBlue
skinparam ActorBorderColor    SaddleBrown


participant ClientPythonScript as A #white
participant ParkingJavaApp as B #white
participant PostgresDB as C #white

A -> B: HTTP request
B <-> C: DB CRUD
B -> A: HTTP response
@enduml
